apiVersion: apps/v1
kind: Deployment
metadata:
  # Nama deployment untuk TI Anda
  name: vehiclerental-be
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      # Label yang harus cocok dengan template di bawah
      app: vehiclerental-be
  template:
    metadata:
      labels:
        # Label untuk pod, digunakan oleh selector di atas
        app: vehiclerental-be
    spec:
      containers:
        - name: vehiclerental-be-container
          # Image dari Docker Hub Anda. REPLACE_ME_TAG akan diisi oleh CI/CD
          image: nairafiany/vehiclerental-2306240124-be:REPLACE_ME_TAG
          ports:
            # Port internal yang diekspos oleh aplikasi Spring Boot Anda
            - containerPort: 8080
          env:
            # Mengambil URL database dari ConfigMap
            - name: DATABASE_URL_PROD
              valueFrom:
                configMapKeyRef:
                  # Nama ConfigMap yang akan dibuat oleh CI/CD
                  name: vehiclerental-be-config
                  key: DATABASE_URL_PROD
            # Mengambil username database dari ConfigMap
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  # Nama ConfigMap yang sama
                  name: vehiclerental-be-config
                  key: DATABASE_USERNAME
            # Mengambil password database dari Secret
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  # Nama Secret yang akan dibuat oleh CI/CD
                  name: vehiclerental-be-secret
                  key: DATABASE_PASSWORD
            # Mengambil JWT secret dari Secret
            # TAMBAHAN: Mengambil CORS origins dari Secret
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                secretKeyRef:
                  # Nama Secret yang sama
                  name: vehiclerental-be-secret
                  key: CORS_ALLOWED_ORIGINS
